FROM resin/%%RESIN_MACHINE_NAME%%-node

MAINTAINER Gergely Imreh <gergely@resin.io>

ENV INITSYSTEM on
WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -qy \
     libcairo2-dev \
     wireless-tools \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY package.json package.json
RUN JOBS=MAX npm install --production --unsafe-perm && npm cache clean && rm -rf /tmp/*

COPY . ./

CMD ./prestart.sh && ./start.sh
